version: '2'

services:
    web:
        build: web
        ports:
            - "80:80"
        restart: always
        networks:
            - main
        volumes:
            - ./web/app:/var/www/html
    mysql:
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "drupal7"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        restart: always
        networks:
            - main
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: "mysql"
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        restart: always
        ports:
            - "8080:80"
        links:
            - mysql
        volumes:
            - /sessions
        networks:
            - main

networks:
    main:
        driver: bridge
